BaseConfig:
  device: 'cpu'
  batch_size: 16
  num_epochs: 3
  learning_rate: 0.0003
  adam_betas: (0.95, 0.99)
  test_size_percentage: 0.05
  predictor_period: 30 # length of period of data that will be input for model
  forecast_period: 1

UserConfig:
  ... # put here all you need to initialize a model